language: node_js
node_js:
  - '10'
  - 10.15.0

cache:
  directories:
    - $HOME/.npm

install:
  - npm ci
script:
  - CI=false npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "YvNL/hYHbfaqWMwXtVGsRewg52UF8DAioI9GRlQ5lLpL4nnJ9kCN0xBpOFSMEw25UKXNZlbQiXceIVLwwhMgJJOti75scY1t/XYqTGI8IdWLRiqW/D4Nza/AHQ6IB4ZjkHtigVIDSBUIjh3db4ssC/LbdstoclHM95pFKuWGOVm0xlJy/xECEEYbGoaS82+uznejMpE3XCL6Q02nKRS4XiaUp/rEOsd6osmiR/JQKLu3Lgrhhj8ErDpz1vDM5waXlMrzE3TRPRPBD7pl9FsuPIMjMrcZKFeXEKNCaKzl3QBQCsVz/jXlymF6WNc0CC25U6XSLaXRiLwVBsMb3myc4oCyHKjnR2ulCpkq5ImQnzFMs/64RSUn1S2LCk56H8e24T3UgkcZWQMuYpk1imFXKF8gj6p0vTMA1Je5JF5tMQZJ3D686u72uM+VS1u3HfA0VUomB6KI3MOmLYjsadJ4TOgFj79KK4Boy/+eBcLCFKF5axIYXHqRQDnDg78L6UdQ31/Llly/uzg91hmhIVgH1sCjWYHOnpXWWfVL/XJI1zo2iI80VCOTGtj0CKIe5x8unfLMGi+/ytwVTE5DT4rI8zAKcjRW7Ln+jZq4Glj7UHvgP7SZtt1oqYeQIl/PaN+aJLJIbLlAPtr7Qo7Oa2z/fJ0mynLjF659w2b010k1xXs="
